# Generated by Django 5.1.6 on 2025-05-31 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0002_alter_label_id_alter_label_unique_together"),
        ("notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, related_name="shared_notes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="notes", to="labels.label"
            ),
        ),
    ]
